### ISSUE TITLE
unify nomenclature for incidence-angle

### ISSUE THREAD

**Issue by raphaelquast** [pygeo/rt1#13]
within the code, the use of  theta_0 , theta_i and mu_0 
is not fully consistent, evident from definitions such as:
- theta_i = np.arccos(mu_0)
- def thetap(self, thetai, thetas, phii, phis, a=[-1.,1.,1.])    
              which is actually defined to represent thetap with zenith-angle arguments (theta_0, theta_s)

-> this needs to be corrected in order to be able to write a consistent documentation

**Comment by raphaelquast** [comment]
new nomenclature introduced in unified_nomenclature branch.
   - tests and examples adapted and working

**Comment by bulli92** [comment]
branch was merged
