### ISSUE TITLE
correct BRDF normalization

### ISSUE THREAD

**Issue by raphaelquast** [pygeo/rt1#14]
fix standard BRDF normalizations such that they are consistent for the isotropic case, i.e.
- **Isotropic := NormBRDF / pi**
- **HenyeyGreenstein(t=0) = Isotropic = NormBRDF /pi**
           - currently we have: HenyeyGreenstein(t=0) = N / (4pi)
- **CosineLobe(i=0) = Isotropic = NormBRDF/pi**
         - currently we have: CosineLobe(i=0) =NormBRDF

-> adapt tests to fit to the new normalizations

**Comment by raphaelquast** [comment]
can be done easily after merge of generalized_scattering_angle branch,
where the NormBRDF factor is already implemented.

-> a switch from using
    `Cosinelobe(i = __ , ncoefs = __ ) `   to   
    `Cosinelobe(i = __ , ncoefs = __ , NormBRDF = np.pi  )`    within the tests 
     (after changing to the new nomalizations) should keep them performing correctly

**Comment by raphaelquast** [comment]
-> everything implemented in generalized_scattering_angle-branch,
     ready for merging

**Comment by bulli92** [comment]
branch was merged and additional tests were implemented
