### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bulli92** [pygeo/rt1#5]
add more comprehensive documentation and link to READTHEDOCS

**Comment by bulli92** [comment]
link to readthedocs was added

**Comment by bulli92** [comment]
created specific branch for documentation only https://github.com/pygeo/rt1/tree/documentation

**Comment by bulli92** [comment]
doctoring within the code should follow the bumpy convention
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by bulli92** [comment]
I have implemented a first example in a jupyter notebook (https://github.com/pygeo/rt1/blob/documentation/doc/examples/example01.ipynb).

@raphaelquast , can you you please look on the todo therein. There is still some legend needed and the BRDF plot could be perhaps improved in its look.

**Comment by raphaelquast** [comment]
@bulli92 todo-list completed!
concerning the BRDF-plot, since this is rather subjective I added an option to choose the 
color of the lower hemisphere (default is now transparent)
