### ISSUE TITLE
Validate against paper results

### ISSUE THREAD

**Issue by bulli92** [pygeo/rt1#6]
Still not 100% sure if same results like in paper are produced; validate again

**Comment by raphaelquast** [comment]
Plots in paper might not be correct.
Check of results via numerical evaluation of interaction-integral necessary to 
ensure correctness of the results.

**Comment by bulli92** [comment]
implement numerical test routines in test_examples.py

**Comment by raphaelquast** [comment]
added new test with numerical routine in test_examples_int.py

test_examples.py is now obsolete
(I didn't delete it since I didn't create it... if it's no longer needed it can be removed)

**Comment by bulli92** [comment]
solved
